import type { GetServerSideProps } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useContext } from "react";
import CardProduct from "../components/CardProduct/CardProduct";
import { AuthContext } from "../contexts/Auth/AuthContext";
import { api } from "../hooks/useApi";
import { ProductsRequest } from "../models/Products";
import styles from "../styles/Home.module.scss";

interface Products {
  products: ProductsRequest;
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const service = await api.get("/products");
  const products = await service.data;

  console.log(products);

  return {
    props: { products },
  };
};

const Home = ({ products }: Products) => {
  const auth = useContext(AuthContext);
  const router = useRouter();

  console.log(products.products);

  return (
    <>
      <Head>
        <title>Eccomerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        {products.products.map((product, index) => (
          <div key={index}>
            <CardProduct product={product} />
          </div>
        ))}
      </div>
    </>
  );
};

export default Home;
